categories:
  - title: 'ğŸš€ Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'high priority'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'ğŸ“ Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: 'ğŸ§° Maintenance'
    labels:
      - 'chore'
      - 'refactor'
  - title: 'ğŸ’» Technology Updates'
    labels:
      - 'python'
      - 'js'
      - 'Javascript'
      - 'html'
      - 'excel'
      - 'xbrl'
  - title: 'ğŸ¨ UI/UX'
    labels:
      - 'web design'
      - 'web app'
  - title: 'ğŸ“¦ Other Changes'  # Default category
    labels:
      - '*'  # Catch-all for PRs with no matching labels

template: |
  ## Changes
  ${{CHANGELOG}}

  ## Contributors
  ${{CONTRIBUTORS}}

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
sort-by: 'title'
sort-direction: 'ascending' 